### ISSUE TITLE
SAWarning from sqlalchemy

### ISSUE THREAD

**Issue by poupryc** [fastapi/sqlmodel#189]
### First Check

- [X] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
No code
```

### Description

Every time I use the SQLModel ORM, I get this warning.

```
/.../sqlmodel/orm/session.py:60: SAWarning: Class SelectOfScalar will not make use of SQL compilation caching as it does 
not set the 'inherit_cache' attribute to ``True``.  This can have significant performance implications including some 
performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make 
use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which will disable this 
warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  results = super().execute(
```

A [link is given](https://sqlalche.me/e/14/cprf).

### Operating System

Linux

### Operating System Details

Linux 5.15.7-arch1-1 x86_64 GNU/Linux

### SQLModel Version

0.0.4

### Python Version

Python 3.9.9

### Additional Context

The only other reference to this problem that I have found is this one
https://github.com/tiangolo/sqlmodel/issues/129#issuecomment-991074972

**Comment by postpersonality** [comment]
I've solved mine by importing select() from sqlalchemy directly.

**Comment by BurnySc2** [comment]
> I've solved mine by importing select() from sqlalchemy directly.

Be aware that if you select a single value, you will still get a tuple in return, e.g.:
```py
# with 'select' from sqlmodel
with Session(engine) as session:
    count_statement = select(func.count()).select_from(Book).where(Book.release_year < 1960)
    amount = session.exec(count_statement).first()
    assert amount == 2
```
This needs to be `assert amount == (2, )` if you use the `select` from sqlalchemy.

**Comment by mfrey777** [comment]
Is importing select() from sqlalchemy really a solution to this, it don't see the point of using SQLModel and then bypassing it on all select statements. ? Is there a parameter/settings that need to be set somewhere to activating the caching ?

**Comment by chriswhite199** [comment]
While i can't tell you why, the following amendment resolves this warning for me:

```python3
# raises the SAWarning
session.query(MyModel).where(MyModel.field1 == 'value').first()

# Does not raise the warning
from sqlmodel import col
session.query(MyModel).where(col(MyModel.field1) == 'value').first()
```

**Comment by curtwagner1984** [comment]
> Is importing select() from sqlalchemy really a solution to this, it don't see the point of using SQLModel and then bypassing it on all select statements. ? Is there a parameter/settings that need to be set somewhere to activating the caching ?

Did you find an answer?



> While i can't tell you why, the following amendment resolves this warning for me:
> 
> ```python
> # raises the SAWarning
> session.query(MyModel).where(MyModel.field1 == 'value').first()
> 
> # Does not raise the warning
> from sqlmodel import col
> session.query(MyModel).where(col(MyModel.field1) == 'value').first()
> ```

What happens when you don't need a `col`? Like in :

```python
with Session(engine) as session:
  stmt = select(MyModel)
  results = session.exec(stmt).all()
```

**Comment by Gladrat** [comment]
I haven't found any way to disable caching for now.
And the same issue occurs even when not using `col`.

**Comment by angel-langdon** [comment]
Same issue

**Comment by cazdlt** [comment]
Same here :)

**Comment by Tombrilluin** [comment]
Same issue...

**Comment by masreplay** [comment]
@tiangolo same

**Comment by maresb** [comment]
Hi everyone, please stop replying with "same" without contributing more info, that is what the 👍 button at the top is for. Doing so generates spam for everyone who is subscribed, and wastes the valuable time of people like tiangolo.

Using the 👍 button in this way is generally considered good etiquette across all of GitHub. Thanks, and I also hope that someone comes up with a solution soon. 😃

**Comment by mmlynarik** [comment]
> Hi everyone, please stop replying with "same" without contributing more info, that is what the 👍 button at the top is for. Doing so generates spam for everyone who is subscribed, and wastes the valuable time of people like tiangolo.
> 
> Using the 👍 button in this way is generally considered good etiquette across all of GitHub. Thanks, and I also hope that someone comes up with a solution soon. 😃

Do you know what is the reason for the warning? Maybe @tiangolo could know the answer.

**Comment by mmlynarik** [comment]
> Hi everyone, please stop replying with "same" without contributing more info, that is what the 👍 button at the top is for. Doing so generates spam for everyone who is subscribed, and wastes the valuable time of people like tiangolo.
> 
> Using the 👍 button in this way is generally considered good etiquette across all of GitHub. Thanks, and I also hope that someone comes up with a solution soon. 😃
> 
> EDIT: LOL, what is going on here? Is this GitHub or Facebook? I'm not sure whether or not @mmlynarik is trolling. 😂 I'm just subscribed to this thread, hoping for a solution, and getting mildly disappointed each time I receive a notification for a pointless message. I'm not particularly motivated to try and solve this issue myself. I do however have a suggestion...
> 
> If you are so eager for tiangolo to fix this issue, then rather than spamming him, please consider showing him some ❤️ with the Sponsor button at the bottom. I'd really love to see FOSS maintainer become a more viable career choice.

You can check the list of sponsors, you will find my name on it.

**Comment by SamEdwardes** [comment]
Not a long term solution, but if you want to filter out the error for now you can use the following snippet:

```python
import warnings
warnings.filterwarnings("ignore", ".*Class SelectOfScalar will not make use of SQL compilation caching.*")
```

**Comment by memark** [comment]
I would be happy to set the mentioned attribute `inherit_cache` to get rid of the warning. How would I do that?

Following the link in the error
https://sqlalche.me/e/14/cprf
gives some background, but no instruction on where or how to set the attribute.

**Comment by leynier** [comment]
The solution I found was that the `inherit_cache` field should be set in the `Select` and `SelectOfScalar` classes of `sqlmodel.sql.expression`.

![image](https://user-images.githubusercontent.com/36774373/151710100-9f72ee35-780a-428c-8fdc-215a01bd4dd2.png)

Personally, while it is fixed, I will set that field in my code in the following way.

```python
SelectOfScalar.inherit_cache = True  # type: ignore
Select.inherit_cache = True  # type: ignore
```

**Comment by rabinadk1** [comment]
Just a friendly ping to @tiangolo.

**Comment by simbadmorehod** [comment]
> The solution I found was that the `inherit_cache` field should be set in the `Select` and `SelectOfScalar` classes of `sqlmodel.sql.expression`.
> 
> ![image](https://user-images.githubusercontent.com/36774373/151710100-9f72ee35-780a-428c-8fdc-215a01bd4dd2.png)
> 
> Personally, while it is fixed, I will set that field in my code in the following way.
> 
> ```python
> from sqlmodel.sql.expression import Select, SelectOfScalar
> 
> SelectOfScalar.inherit_cache = True  # type: ignore
> Select.inherit_cache = True  # type: ignore
> ```
**ModuleNotFoundError: No module named 'sqlmodel'**

Does anyone have an actual solution?

**Comment by synodriver** [comment]
I'm afraid it's not just a warning. I hava some tables bellow:
```
class Game(SQLModel, table=True):
    __tablename__ = "game"
    game_id: Optional[int] = Field(None, primary_key=True)
    game_sale_time: Optional[datetime]
    game_translated_sale_time: Optional[datetime]
    game_collect_time: Optional[datetime]
    game_size: Optional[int]
    game_show_flag: Optional[int]
    game_delete_flag: Optional[int]
    game_index: Optional[int]
    game_name: str
    filesave: Optional["FileSave"] = Relationship(back_populates="game", sa_relationship_kwargs={"lazy": 'selectin'})


class FileSave(SQLModel, table=True):
    __tablename__ = "universal_file_save"
    universal_file_save_id: int = Field(None, primary_key=True)
    universal_file_save_a: Optional[int]
    universal_file_save_b: Optional[int] = Field(None, foreign_key="game.game_id")  # gameId
    universal_file_save_c: Optional[int]
    universal_file_save_url: Optional[str]
    universal_file_save_remark: Optional[int]
    universal_file_save_title: Optional[int]
    universal_file_save_rank: Optional[int]
    universal_file_save_show_flag: Optional[int]
    universal_file_save_delete_flag: Optional[int]
    game: Optional[Game] = Relationship(back_populates="filesave", sa_relationship_kwargs={"lazy": 'selectin'})
```
With sqlmodel==0.0.6, SQLAlchemy==1.4.26 and using async mod, it wors fine. However with SQLAlchemy==1.4.36, not only I got this warning from SQLAlchemy, but also I found ```Game.filesave``` missing, the query result just not have the ```filesave``` attriubte. That means you may found yourself lossing some foreign keys in the result if you seen this warning and you are using async mod.

**Comment by linpan** [comment]
> I've solved mine by importing select() from sqlalchemy directly.

have effect side, [{'a': {}}]

**Comment by tiangolo** [comment]
Thanks for the report! This was solved in https://github.com/tiangolo/sqlmodel/pull/234, it will be available in SQLModel `0.0.7`, released in the next hours.

If some of you would like to help me maintain SQLModel, it would be much appreciated! What I need help with the most is answering questions from others in issues. Thanks! :cake:

**Comment by JonasR** [comment]
I just upgraded to SQLModel `0.0.7` (and SQLAlchemy `1.4.40`) and still get this warning. Am I the only one?

**Comment by memark** [comment]
Yeah, this is not working for me either. (Maybe that's why the bug was reopened?)

<img width="833" alt="image" src="https://user-images.githubusercontent.com/318504/187064083-671b9b58-b5cb-4491-aba0-6899cd3dfc55.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/318504/187064094-cafb0f05-0ac1-4ccf-b67d-af0a1e5cbf8f.png">

**Comment by JonasR** [comment]
It seems the fix was only applied to [`expression.py.jinja2`](https://github.com/tiangolo/sqlmodel/blob/main/sqlmodel/sql/expression.py.jinja2), not [`expression.py`](https://github.com/tiangolo/sqlmodel/blob/main/sqlmodel/sql/expression.py)
Not sure if that was intentional.

**Comment by rabinadk1** [comment]
> It seems the fix was only applied to [`expression.py.jinja2`](https://github.com/tiangolo/sqlmodel/blob/main/sqlmodel/sql/expression.py.jinja2), not [`expression.py`](https://github.com/tiangolo/sqlmodel/blob/main/sqlmodel/sql/expression.py) Not sure if that was intentional.

I had only changed the jinja one due to this line at the top of the python file.
`# WARNING: do not modify this code, it is generated by expression.py.jinja2`

**Comment by JonasR** [comment]
I guess that makes sense. I have no idea how exactly the release works here. It looks to me like [generate_select.py](https://github.com/tiangolo/sqlmodel/blob/main/scripts/generate_select.py) was supposed to have been executed at some point but wasn't.

**Comment by tiangolo** [comment]
Ah! Thanks everyone, good point @rabinadk1, I fixed it in https://github.com/tiangolo/sqlmodel/pull/422, I also made a test that ensures the file is up to date with the Jinja2 template.

This will be available in the next version, in some hours. SQLModel `0.0.8`. :rocket:

**Comment by nickatnight** [comment]
Can this be closed?

**Comment by memark** [comment]
@nickatnight Yes, this is now working as expected. The warning is no longer shown.
